- name: Installing Jenkins Server
  hosts: jenkins-server
  become: true
  tasks:
  - name: Install required dependencies (wget, curl, gnupg, ca-certificates)
    apt:
      update_cache: yes
      name:
      - wget
      - curl
      - gnupg
      - ca-certificates
      state: present

  - name: Add Jenkins keyring
    get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins repository to apt sources list
    lineinfile:
      path: /etc/apt/sources.list.d/jenkins.list
      line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]
        https://pkg.jenkins.io/debian binary/"
      create: yes

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install jdk17 and Jenkins
    apt:
      update_cache: yes
      name:
      - fontconfig
      - openjdk-17-jre
      - jenkins
      state: present
