- name: Installing Jenkins Server
  hosts: jenkins-server
  become: true
  tasks:
  - name: Install required dependencies (wget, curl, gnupg, ca-certificates)
    apt:
      update_cache: yes
      name:
      - wget
      - curl
      - gnupg
      - ca-certificates
      state: present

  - name: Add Jenkins keyring
    get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins repository to apt sources list
    lineinfile:
      path: /etc/apt/sources.list.d/jenkins.list
      line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]
        https://pkg.jenkins.io/debian binary/"
      create: yes

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install jdk17
    apt:
      update_cache: yes
      name:
      - fontconfig
      - openjdk-17-jre
      state: present

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

  - name: Create directory for Docker GPG key
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Docker's official GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Get the architecture
    command: dpkg --print-architecture
    register: dpkg_arch

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
        https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }}
        stable"
      filename: docker
      state: present

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install Docker and Containerd
    apt:
      update_cache: yes
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: present

  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Add jenkins user to docker group
    user:
      name: "jenkins"
      groups: docker
      append: yes

  - name: Enable and start Docker services
    systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
    - docker.service
    - containerd.service

  - name: Install kubectl
    shell: |
      curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/bin/kubectl
      chmod a+x /usr/bin/kubectl
      kubectl version
