- name: Installing Jenkins Server
  hosts: jenkins-server
  become: true
  tasks:
  - name: Install required dependencies (wget, curl, gnupg, ca-certificates)
    apt:
      update_cache: yes
      name:
      - wget
      - curl
      - gnupg
      - ca-certificates
      state: present

  - name: Add Jenkins keyring
    get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
      mode: '0644'

  - name: Add Jenkins repository to apt sources list
    lineinfile:
      path: /etc/apt/sources.list.d/jenkins.list
      line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]
        https://pkg.jenkins.io/debian binary/"
      create: yes

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install jdk17
    apt:
      update_cache: yes
      name:
      - fontconfig
      - openjdk-17-jre
      state: present

  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

  - name: Install kubectl
    shell: |
      curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/bin/kubectl
      chmod a+x /usr/bin/kubectl

  - name: Add the PPA repository for yq
    apt_repository:
        repo: ppa:rmescandon/yq
        state: present
        
  - name: Remove stale lock files
    shell: rm -rf /var/lib/apt/lists/lock;rm -rf /var/cache/apt/archives/lock;rm -rf
      /var/lib/dpkg/lock*
  
  - name: Install yq
    apt:
        name: yq
        state: present
        update_cache: yes
